name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Replace properties with environment variables
      run: |
            echo "spring.datasource.url=${{ secrets.DB_URL }}" > src/main/resources/application.properties
            echo "spring.datasource.username=${{ secrets.DB_USERNAME }}" >> src/main/resources/application.properties
            echo "spring.datasource.password=${{ secrets.DB_PASSWORD }}" >> src/main/resources/application.properties
            echo "spring.datasource.driver-class-name=org.postgresql.Driver" >> src/main/resources/application.properties
            echo "spring.application.name=spring-supabase-practice-app" >> src/main/resources/application.properties
            echo "mybatis.type-aliases-package=com.example.app.model" >> src/main/resources/application.properties
            echo "logging.level.root=INFO" >> src/main/resources/application.properties
            echo "logging.level.com.example.app=DEBUG" >> src/main/resources/application.properties
            echo "logging.level.org.springframework.web=DEBUG" >> src/main/resources/application.properties
            echo "logging.level.org.springframework.security=DEBUG" >> src/main/resources/application.properties
            echo "spring.session.store-type=none" >> src/main/resources/application.properties
            echo "spring.datasource.hikari.data-source-properties.cachePrepStmts=true" >> src/main/resources/application.properties
            echo "spring.datasource.hikari.data-source-properties.prepStmtCacheSize=250" >> src/main/resources/application.properties
            echo "spring.datasource.hikari.data-source-properties.prepStmtCacheSqlLimit=2048" >> src/main/resources/application.properties
            echo "spring.datasource.hikari.maximum-pool-size=10" >> src/main/resources/application.properties
      env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  
    - name: Build with Maven
      run: mvn clean package -P war

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VPS_KEY }}

    - name: Copy WAR to VPS
      run: |
          WAR_FILE=$(ls target/*.war)
          echo "WAR file: $WAR_FILE"
          scp -P ${{ secrets.VPS_PORT }} -o StrictHostKeyChecking=no $WAR_FILE ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/root/debug/target/spring-supabase-practice-app.war
  
    - name: Deploy to VPS
      run: |
          ssh -p ${{ secrets.VPS_PORT }} -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /root/debug
            docker-compose down
            docker-compose up --build -d
          EOF
